### ISSUE TITLE
css-loader分析

### ISSUE THREAD

**Issue by wsqviva** [wsqviva/wsqviva.github.io#32]
## 前言
之前初步探究了下webpack-hot-middleware，由于是非官方的库，让我有点小不爽，今天来探究一下官方的一个小库，[css-loader](https://github.com/webpack/css-loader) v0.26.1

## 项目结构
![structure](https://wsqviva.github.io/css-loader/images/structure.png)

其中高亮的为，css-loader的主文件

## demo
假设demo项目的绝对路径`/Users/wsqviva/css-loader-demo`

`src/reset.css`
```css
* {
  margin: 0;
  padding: 0;
}

.fl {
  float: left;
}

.fr {
  float: right;
}
```

`color.css`
```css
.cl-red {
  color: red;
}

.cl-green {
  color: green;
}

.cl-blue {
  color: blue;
}
```

`src/hello.css`
```css
@import './reset.css' screen;

h1 {
  font-family: "Helvetica Neue";
}

:local(.abc) {
  // 注意compose后面要加s
  composes: cl-red from './color.css';
  background: url(../imgs/7.jpeg) no-repeat;
}
```

`src/index.js`
```javascript
require('./hello.css')
```

`webpack.config.js`
```javascript
module: {
  loaders: [
    // 因为css需要用css-modules的写法，所以这里传个参数module(s)
    { test: /\.css$/, exclude: /node_modules/, loaders: ['style-loader', 'css-loader?modules'] }
  ]
}
```

## Source code分析
**processCss.js**
`引入postcss插件`
```javascript
var localByDefault = require("postcss-modules-local-by-default");
var extractImports = require("postcss-modules-extract-imports");
var modulesValues = require("postcss-modules-values");
var modulesScope = require("postcss-modules-scope");
```

`后处理css`
```javascript
/**
 * @param inputSource
 * @param inputMap
 * @param options
 *  { 
 *    mode: moduleMode ? "local" : "global",
 *    from: loaderUtils.getRemainingRequest(this),
 *    to: loaderUtils.getCurrentRequest(this),
 *    query: query,
 *    minimize: this.minimize,
 *    loaderContext: this
 *  }
 */
module.exports = function processCss(inputSource, inputMap, options, callback) {
  // 见下面分析
};
```

`调用插件` 注意下，由于这里有3个css文件，所以会被调用三次

```javascript
var query = options.query;
var root = query.root;
var context = query.context;
var localIdentName = query.localIdentName || "[hash:base64]";
var localIdentRegExp = query.localIdentRegExp;
var forceMinimize = query.minimize;
var minimize = typeof forceMinimize !== "undefined" ? !!forceMinimize : options.minimize;

var customGetLocalIdent = query.getLocalIdent || getLocalIdent;

// 这里其值为{ root: undefined, mode: 'global', url: true, import: true }
var parserOptions = {
  // css-loader的参数root的值
  root: root,
  // css-loader的参数module(s)的值，query.modules || query.module ? "local" : "global"
  mode: options.mode,
  // query.url为css-loader的参数url的值
  url: query.url !== false,
  // query.import为css-loader的参数import的值
  import: query.import !== false
};

var pipeline = postcss([
  localByDefault({
    // global
    mode: options.mode,
    /*
     global: true
     url: ../imgs/7.jpeg
    */
    rewriteUrl: function(global, url) {
      if(parserOptions.url){
        // 判断url是否为一个request，排除以下
        // data:格式，https//，http://，//格式，某些模板格式如{}，<%%>...
        // 未设置root并且是一个/xxx绝对路径
        if(!loaderUtils.isUrlRequest(url, root)) {
          return url;
        }
        if(global) {
          // 将url转为webpack module request
          // 不过这里转换后仍然是../imgs/7.jpeg
          return loaderUtils.urlToRequest(url, root);
        }
      }
      return url;
    }
  }),
  extractImports(),
  modulesValues,
  modulesScope({
    generateScopedName: function generateScopedName (exportName) {
      // exportName为abc
      return customGetLocalIdent(options.loaderContext, localIdentName, exportName, {
        regExp: localIdentRegExp,
        hashPrefix: query.hashPrefix || "",
        context: context
      });
    }
  }),
  parserPlugin(parserOptions)
]);

// ... 
// pipeline.process(inputSource, { ... }).then(function(result) { ... }).catch(function(err) { ... })
// ...
```

一个一个说明各插件的作用：
* [postcss-modules-local-by-default](https://github.com/css-modules/postcss-modules-local-by-default) README只给了简单介绍，从中看出只要没明确标注global的类全转为:local(.xxx), 明确标注:global的类，直接去掉:global

那么经过此插件后
原因：`因为传了module(s)选项，后面再调用此插件，则选择了local模式`
`src/reset.css` 
```css
* {
  margin: 0;
  padding: 0;
}

:local(.fl) {
  float: left;
}

:local(.fr) {
  float: right;
}
```

`color.css`
```css
:local(.cl-red) {
  color: red;
}

:local(.cl-green) {
  color: green;
}

:local(.cl-blue) {
  color: blue;
}
```

* [postcss-modules-extract-imports](https://github.com/css-modules/postcss-modules-extract-imports)

这样经过此插件后
`src/index.css`
```css
:import("./color.css"){
  i__imported_cl_red_0: cl-red;
}

@import './reset.css' screen;

h1 {
  font-family: "Helvetica Neue";
}

:local(.abc) {
  composes: i__imported_cl_red_0;
  background: url(../imgs/7.jpeg) no-repeat;
}
```

* [postcss-modules-values](https://github.com/css-modules/postcss-modules-values), 其为css-modules的@value变量用法

* [postcss-modules-scope](postcss-modules-scope)

经过此插件后
`src/index.css`
```css
:import("./color.css"){
  i__imported_cl_red_0: cl-red;
}

@import './reset.css' screen;

h1 {
  font-family: "Helvetica Neue";
}

:export {
  abc: hDlJs4pgllnpDBboYXZu8;
}

.hDlJs4pgllnpDBboYXZu8 {
  compose: i__imported_cl_red_0;
  background: url(../imgs/7.jpeg) no-repeat;
}
```

`src/reset.css`
```javascript
* {
  margin: 0;
  padding: 0;
}

.SG-DXmiz9NQEBCHUbOTGl {
  float: left;
}

._6x3K_5Cj2G-BpdYC60byG {
  float: right;
}

:export {
  fl: SG-DXmiz9NQEBCHUbOTGl,
  fr: _6x3K_5Cj2G-BpdYC60byG
}
```

`src/color.css`
```
._2sHj2AZqnvOElsNym08yzW {
  color: red;
}

._36-z2B18MWrOp4p5EitRwo {
  color: green;
}

._2stcI7Ew6d0YkMFJ5-n3ao {
  color: blue;
}

:export {
  cl-red: _2sHj2AZqnvOElsNym08yzW,
  cl-green: _36-z2B18MWrOp4p5EitRwo,
  cl-blue: _2stcI7Ew6d0YkMFJ5-n3ao
}
```

* 最后调用自己定义的插件`parserPlugin(parserOptions)`
`定义postcss插件`
```javascript
var parserPlugin = postcss.plugin("css-loader-parser", function(options) {
  return function(css) {
    var imports = {};
    var exports = {};
    var importItems = [];
    var urlItems = [];

    function replaceImportsInString(str) {
      if(options.import) {
        var tokens = str.split(/(\S+)/);
        tokens = tokens.map(function (token) {
          var importIndex = imports["$" + token];
          if(typeof importIndex === "number") {
            return "___CSS_LOADER_IMPORT___" + importIndex + "___";
          }
          return token;
        });
        return tokens.join("");
      }
      return str;
    }

    if(options.import) {
      // 这里index.css有此css规则，@import './reset.css' screen
      // importItems.push({ url: './reset.css', mediaQuery: 'screen' })
      // 并将此条css规则删除
      css.walkAtRules("import", function(rule) {
        var values = Tokenizer.parseValues(rule.params);
        var url = values.nodes[0].nodes[0];
        if(url.type === "url") {
          url = url.url;
        // 走这条判断
        } else if(url.type === "string") {
          url = url.value;
        } else throw rule.error("Unexpected format" + rule.params);
        values.nodes[0].nodes.shift();
        var mediaQuery = Tokenizer.stringifyValues(values);
        if(loaderUtils.isUrlRequest(url, options.root) && options.mode === "global") {
          url = loaderUtils.urlToRequest(url, options.root);
        }
        importItems.push({
          url: url,
          mediaQuery: mediaQuery
        });
        rule.remove();
      });
    }

    css.walkRules(function(rule) {
      // 匹配css规则，为:export选择器
      // index.css, exports['abc'] = 'hDlJs4pgllnpDBboYXZu8'
      // 再将此条规则删除 
      if(rule.selector === ":export") {
        rule.walkDecls(function(decl) {
          exports[decl.prop] = decl.value;
        });
        rule.remove();
      // 匹配css规则，为:import开头的选择器
      // 对index.css
      // imports['$i__imported_cl_red_0'] = 1
      // importItems.push({ url: './color.css', export: 'cl-red' })
      // 再将此条规则删除
      } else if(/^:import\(.+\)$/.test(rule.selector)) {
        var match = /^:import\((.+)\)$/.exec(rule.selector);
        var url = loaderUtils.parseString(match[1]);
        rule.walkDecls(function(decl) {
          imports["$" + decl.prop] = importItems.length;
          importItems.push({
            url: url,
            export: decl.value
          });
        });
        rule.remove();
      }
    });

    Object.keys(exports).forEach(function(exportName) {
      exports[exportName] = replaceImportsInString(exports[exportName]);
    });

    function processNode(item) {
      switch (item.type) {
        case "value":
          item.nodes.forEach(processNode);
          break;
        case "nested-item":
          item.nodes.forEach(processNode);
          break;
        case "item":
          var importIndex = imports["$" + item.name];
          if (typeof importIndex === "number") {
            item.name = "___CSS_LOADER_IMPORT___" + importIndex + "___";
          }
          break;
        case "url":
          if (options.url && !/^#/.test(item.url) && loaderUtils.isUrlRequest(item.url, options.root)) {
            item.stringType = "";
            delete item.innerSpacingBefore;
            delete item.innerSpacingAfter;
            var url = item.url;
            item.url = "___CSS_LOADER_URL___" + urlItems.length + "___";
            urlItems.push({
              url: url
            });
          }
          break;
      }
    }

    css.walkDecls(function(decl) {
      var values = Tokenizer.parseValues(decl.value);
      values.nodes.forEach(function(value) {
        value.nodes.forEach(processNode);
      });
      decl.value = Tokenizer.stringifyValues(values);
    });
    css.walkAtRules(function(atrule) {
      if(typeof atrule.params === "string") {
        atrule.params = replaceImportsInString(atrule.params);
      }
    });

    options.importItems = importItems;
    options.urlItems = urlItems;
    options.exports = exports;
  };
});
```
这里定义了一个postcss的插件，具体postcss插件怎么写，见[postcss仓库介绍](https://github.com/postcss/postcss)

**getLocalIndent.js**

```javascript
var loaderUtils = require("loader-utils");
var path = require("path");

// 这个函数只有hello.css文件走进来
module.exports = function getLocalIdent(loaderContext, localIdentName, localName, options) {
  // 如果css-loader没有参数context
  //    (走这条判断)如果webpack的根据配置生成的context为字符串类型，则为/Users/wsqviva/css-loader-demo
  //    否则为css-loader的context，loader中this.context，实际为这三个css文件对应的绝对路径，这里均为/Users/wsqviva/css-loader-demo/src
  if(!options.context)
    options.context = loaderContext.options && typeof loaderContext.options.context === "string" ? loaderContext.options.context : loaderContext.context;
  // 这里loaderContext.resourcePath为/Users/wusiquan/github/webpack-loader-develop/src/hello.css
  // request为src/hello.css
  var request = path.relative(options.context, loaderContext.resourcePath);
  // 为options添加content属性，其值为src/hello.css+abc
  options.content = options.hashPrefix + request + "+" + localName;
  localIdentName = localIdentName.replace(/\[local\]/gi, localName);
  // 根据localIdentName的token格式及options.content等，替换出插值名称
  // 这里为hDlJs4pgllnpDBboYXZu8
  var hash = loaderUtils.interpolateName(loaderContext, localIdentName, options);
  return hash.replace(new RegExp("[^a-zA-Z0-9\\-_\u00A0-\uFFFF]", "g"), "-").replace(/^((-?[0-9])|--)/, "_$1");
};
```

## loader的选项
* root

* context
调用getLocalIdent用到

* localIdentName
默认是[hash:base64]

* localIdentRegExp

* minimize

* getLocalIdent
为getLocalIdent.js文件定义的函数

* hashPrefix
hash前缀默认为空字符串""
调用getLocalIdent有用到

## 资料
1. [CSS Modules 用法教程](http://www.ruanyifeng.com/blog/2016/06/css_modules.html)
